//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchangeDeLivres.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDetailLivreAjouter> tblDetailLivreAjouters { get; set; }
        public virtual DbSet<tblEtduiant> tblEtduiants { get; set; }
        public virtual DbSet<tblGestionnaire> tblGestionnaires { get; set; }
        public virtual DbSet<tlbLivre> tlbLivres { get; set; }
    }
}
