//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchangeDeLivres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEtduiant
    {
        public decimal IdEtudiant { get; set; }
        public string NomEtudiant { get; set; }
        public string EmailEtd { get; set; }
        public string AdresseEtd { get; set; }
        public string MotPassEtd { get; set; }
    }
}
