//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchangeDeLivres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGestionnaire
    {
        public int IdGestionnaire { get; set; }
        public string NomGestionnaire { get; set; }
        public string EmailGestionnaire { get; set; }
        public string MotPassGestionnaire { get; set; }
        public string AdresseCoop { get; set; }
    }
}
