//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchangeDeLivres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlbLivre
    {
        public int IdLivre { get; set; }
        public string CodeLivre { get; set; }
        public string TitreLivre { get; set; }
        public string AuteurLivre { get; set; }
        public int NbPagesLivre { get; set; }
        public double PrixLivre { get; set; }
    }
}
